title: ZAIZI Ceramic Studio
author: Wu Qiaoling
email: 
description: >-
 Hi, this is my work exhibition
social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
